name: foodsense_ai
description: "AI-Powered Grocery Shopping Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  provider: ^6.1.1
  shared_preferences: ^2.5.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  mobile_scanner: ^7.2.0
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/l10n/tr.json
    - lib/core/l10n/en.json
    - lib/core/l10n/de.json
